### ISSUE TITLE
What does "settings.performance.showallrecommendations" and "user.settings.webinterface" setting do?

### ISSUE THREAD

**Issue by lesar8** [SpotifyXP/SpotifyXP#25]
Hi, so I noticed there is a setting called "settings.performance.showallrecommendations" and "user.settings.webinterface" on the file config.json. I wonder what does these settings do? Thank you.

**Comment by werwolf2303** [comment]
I think the "settings.performance.showallrecommendations" is an old now unused setting I should remove it.
The "user.settings.webinterface" controls if the webinterface should start. It's a minimal effort webinterface for controlling spotifyxp from an other machine without spotify. The reason why I added it is so that I can control the music while I was playing Euro Truck Simulator 2 TruckersMP. You can open it with: http://127.0.0.1:790
