### ISSUE TITLE
It is asking for login but it does not work.

### ISSUE THREAD

**Issue by HIXOXIH** [SpotifyXP/SpotifyXP#50]
I've been using Spotify normally. 
Some errors happen, like it stops playing between tracks, or it stops at "create api" when running it. But so far so good.
The problem is that now when I try to open it, it's asking for a login.
But it was already logged in since the time I logged in and I always logged in without having to do it again.
 And the worst part is that when I enter my access credentials, it goes back to the login screen as if it was wrong. 
How can I solve this?

**Comment by HIXOXIH** [comment]
![Clipboard01](https://github.com/user-attachments/assets/c9200c88-792f-4e72-9de4-c54e3242aad7)

**Comment by WalterKnox** [comment]
I am having this issue as well. It just started yesterday. Before it was signed in and working, now it is asking for me to sign in, but will not allow me to do so, and just keeps popping up with the "sign in" dialogue. I checked to ensure my account was working on  the Spotify website, and I was able to sign in there. This is on my laptop, I have multiple machines running this software, but am not currently home so I am unable to check if this issue is present on my other machines as well.

**Comment by Jri-creator** [comment]
Have you:

1. Deleted the SpotifyXP folder, and
2. Re-installing SpotifyXP?

By doing this, you are essentially resetting SpotifyXP, which helps clear any bad cache stored in program, and creates a new setup, or layout, of how SpotifyXP should interface with the Spotify servers.

**Comment by HIXOXIH** [comment]
> Have you:
> 
> 1. Deleted the SpotifyXP folder, and
> 2. Re-installing SpotifyXP?
> 
> By doing this, you are essentially resetting SpotifyXP, which helps clear any bad cache stored in program, and creates a new setup, or layout, of how SpotifyXP should interface with the Spotify servers.

I haven't done this yet. I'll try tomorrow and let you know if it worked. Thanks

**Comment by werwolf2303** [comment]
Look at the readme. The project is now likely killed because of Spotify
