### ISSUE TITLE
Playback problem

### ISSUE THREAD

**Issue by lesar8** [SpotifyXP/SpotifyXP#6]
Hi, the specific build that you sent me works well. But when trying the latest commit db2f4af, many errors appear when playing song and it occurs very often!

```
[java.lang.Throwable: Failed requesting chunk from network, index: 12] 
[java.util.concurrent.RejectedExecutionException: Task com.spotifyxp.deps.xyz.gianlu.librespot.audio.cdn.CdnManager$Streamer$InternalStream$$Lambda$186/20149895@1fe74a3 rejected from java.util.concurrent.ThreadPoolExecutor@1fbf9e7[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 26]] 
[java.util.concurrent.RejectedExecutionException: Task com.spotifyxp.deps.xyz.gianlu.librespot.audio.cdn.CdnManager$Streamer$InternalStream$$Lambda$186/20149895@1fe74a3 rejected from java.util.concurrent.ThreadPoolExecutor@1fbf9e7[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 26]] 
[java.lang.Throwable: Failed loading track.javax.net.ssl.SSLPeerUnverifiedException: Hostname audio4-gm-fb.spotifycdn.com not verified:
    certificate: sha256/F1cDKqo299xpNogpffCQtgb/TI8o4t+d6mlsIUJgsug=
    DN: CN=audio-gm-off.spotifycdn.com
    subjectAltNames: [audio-gm-off.spotifycdn.com]] 
[java.lang.Throwable: Player failed! retry] 
[java.lang.UnknownError: PanicState in PlayerListener] 
```

The latest commit build size is 65MB, on other hand the specific build binary size is only 54MB. Why is there such a stark difference?

**Comment by werwolf2303** [comment]
Its an SSL Certificate error I think. 

I didn't know the word "stark" exists in English

**Comment by lesar8** [comment]
On the latest commit f964b9d, open the Playback History dialog and click "Remove all" will cause an error:
[java.lang.RuntimeException: java.sql.SQLException: query does not return ResultSet]

Would be great if you can add a right-click "Copy" feature for the "Errors" dialog to copy all the logs available, similar to what's implemented for the Lyric dialog.

**Comment by werwolf2303** [comment]
Ok I will do all of that. A little teaser: I have a custom theme in the works where you can select custom colors

**Comment by lesar8** [comment]
Sounds pretty cool, though i am not particularly fond of tweaking theme-side or switching themes. The "Legacy" theme is basically all I need :-)

Anyway, i got into big problem when SpotifyXP fails to load cover art due to SSL handshake failed. Song sometimes doesn't play too..

`[java.lang.Throwable: Failed getting cover image.javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure] `

**Comment by werwolf2303** [comment]
I cant do anything about it because it only does this on your side.

**Comment by werwolf2303** [comment]
Taken from stack overflow: 

The handshake failure could have occurred due to various reasons:

- Incompatible cipher suites in use by the client and the server. This would require the client to use (or enable) a cipher suite that is supported by the server.
- Incompatible versions of SSL in use (the server might accept only TLS v1, while the client is capable of only using SSL v3). Again, the client might have to ensure that it uses a compatible version of the SSL/TLS protocol.
- Incomplete trust path for the server certificate; the server's certificate is probably not trusted by the client. This would usually result in a more verbose error, but it is quite possible. Usually the fix is to import the server's CA certificate into the client's trust store.
- The cerificate is issued for a different domain. Again, this would have resulted in a more verbose message, but I'll state the fix here in case this is the cause. The resolution in this case would be get the server (it does not appear to be yours) to use the correct certificate.


Since, the underlying failure cannot be pinpointed, it is better to switch on the  -Djavax.net.debug=all flag to enable debugging of the SSL connection established. With the debug switched on, you can pinpoint what activity in the handshake has failed

**Comment by lesar8** [comment]
There is a thread in "librespot-java" project in regards of SSL error. It seems like quite a lot of people encounter it.
https://github.com/librespot-org/librespot-java/issues/742

**Comment by werwolf2303** [comment]
Ok I will implement the workaround

**Comment by werwolf2303** [comment]
I implemented my own workaround

**Comment by lesar8** [comment]
Um well.. I still got that "SSLPeerUnverifiedException" error but it's not a dealbreaker as there is a workaround, just open another song and re-open the song that stops playing. Somewhat harsh, but works.

**Comment by werwolf2303** [comment]
Ok can you send me the error with the line number, please?

**Comment by lesar8** [comment]
Did you mean the log in "Errors" dialog? If so then here it is:

```
[java.lang.Throwable: Player failed! retry] 
[java.lang.Throwable: Player failed! retry] 
[java.lang.UnknownError: PanicState in PlayerListener] 
[java.util.ConcurrentModificationException] 
[java.util.ConcurrentModificationException] 
[java.lang.Throwable: Failed loading track.javax.net.ssl.SSLPeerUnverifiedException: Hostname audio4-gm-fb.spotifycdn.com not verified:
    certificate: sha256/F1cDKqo299xpNogpffCQtgb/TI8o4t+d6mlsIUJgsug=
    DN: CN=audio-gm-off.spotifycdn.com
    subjectAltNames: [audio-gm-off.spotifycdn.com]] 
[java.lang.Throwable: Player failed! retry]
```

**Comment by werwolf2303** [comment]
There must be a warning somewhere like this: 'Blocking .... because of https://github...'. Can you send me this line

**Comment by lesar8** [comment]
Strange but my log doesn't have that line in it. 
One positive thing, i just installed [OpenJDK](https://github.com/ojdkbuild/ojdkbuild) and switch to it as my default Java version, SpotifyXP now loads the cover art image normally!
Still, I did not see that " 'Blocking .... because of https://github...'." line everytime the SSLPeerUnverifiedException error appears.

**Comment by werwolf2303** [comment]
Ok when this problem appears again, please notify me
